### ISSUE TITLE
Actant Mapping

### ISSUE THREAD

**Issue by Yam-inshere** [plant2go/doc#10]
![Image](https://github.com/user-attachments/assets/77e655ff-d049-4f96-ab5e-a82824668936)
Problem: Wie beschaffen wir unsere Materialien und was für Materialien sind sie?
Direct Actants
1. Human Actants
- Team: Wir sind direct actants weil wir müssen mit den Entscheidungen treffen
- Kunden: Die Kunden sind dadurch betroffen, wie wir unsere Materialien beschaffen und was für Materialien sind sie, weil sie das als finales Produkt bekommen werden
- Hersteller von technischen Komponente - Leuchtmittel, Sensorenanbieter: Es hängt davon ab, mit wem wir ein Partnerschaft binden, welche Produkte und Komponente die Hersteller anbieten und wem gefällt unser Projekt
- Unser Produkthersteller: Wir müssen darauf rücksicht nehmen, mit welchen Materialien kann unser Produkthersteller arbeiten
- Gärtnereien: Es hängt davon ab, mit wem wir ein Partnerschaft binden, welche Produkte und Komponente die Gärtnereien anbieten und wem gefällt unser Projekt
 
- ASZ: Um Altkleider und Rucksäcke zu haben, müssen wir auch ein Partnerschaft mit ASZ haben
2. Non-Human Actants
- Preise: Entscheidungsfaktor, unsere Produkte sollten nicht unleistbar sein
- Lieferzeiten: Entscheidungsfaktor, je langer oder unterschiedlicher die Lieferzeiten sind, desto schwerer ist, alles zu koordinieren
- Nachhaltigkeitsaspekt: Unser Produkt soll in jeder Aspekt nachhaltig bleiben, es bringt nichts, wenn ein Material ist recyclet und den andere ist Umweltschädlich
- Gesundheitsaspekt: Die Materialien sollten gesund oder nicht schädlich für Pflanzen sein
- Ästhetische Funktion: Das Produkt soll irgendwie gut aussehen
- Funktionalität: Alle Materialien sollen ihre Funktionen gut erfüllen
- Kompatibilität von Materialien: Die Materialien sollen kompatible mit einander sein
 
Indirect Actants
1. Human Actants
- Naturschützer: Wenn unseres Produkt irgendwie Umweltschädlich wird, könnten das Naturschützer (und andere Personen, die dieses Aspekt für wichtig halten) kritisieren
- Konkurrenz am Markt: Wir sollten es vermeiden, zu ähnliche Materialien und Komponenten zu verwenden, wie vorher andere existierende Produkte, damit es nicht zum Konkurrenz führt
- Andere Geschäftspartner
2. Non-Human Actants
- Umwelt
- Weitere Wirtschaftsfaktoren
- Modetrends

Link zu Actant Mapping: https://uxdesign.cc/tools-for-environment-centered-designers-actant-mapping-canvas-a495df19750e

**Zu definieren:**
- Was ist das Problem, was die Entwicklung unseres Prudukts behindert
- Was ist unser "struggle"

- Direkte Actants: wer ist durch den Problem betroffen
- Direkte Humane Actants: Zielgruppe, Stakeholders, Designers ((uns))
- Direkte Non-Humane Actants: "Environmental" Elemente, Ecosystem

- Indirekte Actants

- Ursache-Effekt Beziehungen: zwischen Humane und Non-Humane Actants

**Comment by lydiareiter** [comment]
@Yam-inshere i did the review
