### ISSUE TITLE
Personas erstellen

### ISSUE THREAD

**Issue by lydiareiter** [plant2go/doc#2]
Zu erstellen sind 2 humane Personas und eine non-humane Persona.

Template: 
Non-Human: https://app.conceptboard.com/board/eq87-1a10-nhm4-kfap-er07

Human: https://app.conceptboard.com/board/eq87-1a10-nhm4-kfap-er07
https://app.conceptboard.com/board/32ka-ara8-erba-enqd-78m5

PND Slides zu Personas: https://github.com/plant2go/doc/tree/main/doc/Slides_PND

Sub-Tasks:
Non-human: https://github.com/orgs/plant2go/projects/1/views/1?pane=issue&itemId=87268041

Human: https://github.com/orgs/plant2go/projects/1/views/1?pane=issue&itemId=87269624

[Empathy Map](https://elearning.fh-ooe.at/mod/url/view.php?id=506820)

**Comment by lydiareiter** [comment]
doc#2

**Comment by Yam-inshere** [comment]
Liebe Studierende,

was ich gestern noch vergessen habe, zu erwähnen:

Sie können für die Erstellung der Personas auch z. B. eine Empathy Map heranziehen:
siehe u. a. Block 3 - dort ist ein Link eingestellt, wo Sie ein sehr gute Vorlage und Erläuterung dafür finden:

Gutes Gelingen wünscht Ihnen
Gudrun Heinzelreiter-Wallenr

**Comment by Yam-inshere** [comment]
@lydiareiter review
