### ISSUE TITLE
doc: schreiben 14.11.2024

### ISSUE THREAD

**Issue by lydiareiter** [plant2go/doc#6]

**Comment by lydiareiter** [comment]
SUB: https://github.com/orgs/plant2go/projects/1/views/1?pane=issue&itemId=87265602

**Comment by lydiareiter** [comment]
SUB: https://github.com/orgs/plant2go/projects/1/views/1?pane=issue&itemId=87264593

**Comment by lydiareiter** [comment]
@lenapopena bitte review - markiere dich auch noch auf den sub tasks. Also wenn dieses Ticket passt dann kannst du auch die Sub auf Done geben

hab mehr als heute bearbeitet also bitte kurz sonst auch noch drüber schauen ob es logisch ist

**Comment by lenapopena** [comment]
reviewed subs - done
