### ISSUE TITLE
SUB: Feedback in Doc

### ISSUE THREAD

**Issue by lydiareiter** [plant2go/doc#7]
Prof. Feedback einarbeiten vom 14.11.2024

**Comment by lydiareiter** [comment]
@Yam-inshere kann ich bitte deine Mitschrift bekommen?

**Comment by Yam-inshere** [comment]
•	Absolute Zahlen keine Prozentangaben
•	Stakeholder etwas von außen in die Mitte
•	Beim Fragebogen wären Verzweigungen möglich
•	Rucksack - 1x mit 2 S
•	Interview besser als Umfrage

**Comment by lydiareiter** [comment]
@lenapopena review

**Comment by lenapopena** [comment]
review done
