### ISSUE TITLE
SUB: Präsentationsfeedback in Doc einarbeiten

### ISSUE THREAD

**Issue by lydiareiter** [plant2go/doc#8]
Wir haben auf Miro Feedback bekommen. Dieses Feedback sollte in unsere Dokumentation einerbeitet werden mittels Asci Doc

**Comment by Yam-inshere** [comment]
Gendern -  wenn einmal, dann überall
Lieferanten/Innen
zB

**Comment by lydiareiter** [comment]
@lenapopena review bitte - danke :)

**Comment by lenapopena** [comment]
review done
